use std::collections::BTreeMap;
use std::env;
use std::fs::File;
use std::io::{BufWriter, Write};
use std::path::PathBuf;

fn main() {
    let data_path = PathBuf::from("data/species_growth.json");
    println!("cargo:rerun-if-changed={}", data_path.display());
    println!("cargo:rerun-if-changed=build.rs");

    let json_bytes = std::fs::read(&data_path)
        .unwrap_or_else(|e| panic!("Kann {} nicht lesen: {}", data_path.display(), e));
    let json: serde_json::Value =
        serde_json::from_slice(&json_bytes).expect("species_growth.json ist kein gültiges JSON");

    let species = json
        .get("species")
        .and_then(|v| v.as_object())
        .expect("species_growth.json: Top-level Key 'species' fehlt");

    // Sortierte Map für deterministische Codegen-Output
    let mut sorted: BTreeMap<u16, &str> = BTreeMap::new();
    for (k, v) in species {
        let id: u16 = k
            .parse()
            .unwrap_or_else(|e| panic!("Species-ID '{}' ist kein u16: {}", k, e));
        let slug = v
            .as_str()
            .unwrap_or_else(|| panic!("Wert für Species {} ist kein String", id));
        sorted.insert(id, slug);
    }

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR not set"));
    let out_path = out_dir.join("species_growth.rs");
    let mut out = BufWriter::new(File::create(&out_path).expect("Cannot create codegen file"));

    writeln!(
        out,
        "// AUTO-GENERATED by build.rs from data/species_growth.json — do not edit.\n\
         use crate::game::growth_rates::GrowthRate;\n"
    )
    .unwrap();

    let mut builder = phf_codegen::Map::<u16>::new();
    for (id, slug) in &sorted {
        let variant = match *slug {
            "erratic" => "GrowthRate::Erratic",
            "fast" => "GrowthRate::Fast",
            "medium" | "medium-fast" => "GrowthRate::MediumFast",
            "medium-slow" => "GrowthRate::MediumSlow",
            "slow" => "GrowthRate::Slow",
            "fluctuating" => "GrowthRate::Fluctuating",
            other => panic!(
                "species_growth.json: unbekannter slug '{}' für Species {}",
                other, id
            ),
        };
        builder.entry(*id, variant);
    }

    writeln!(
        out,
        "pub static SPECIES_GROWTH: phf::Map<u16, GrowthRate> = {};",
        builder.build()
    )
    .unwrap();
}
